# Generated by Django 5.2.8 on 2025-12-03 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('gearbox', models.CharField(max_length=50)),
                ('doors', models.PositiveSmallIntegerField()),
                ('seats', models.PositiveSmallIntegerField()),
                ('equipments', models.JSONField(blank=True, default=list)),
                ('mileage', models.PositiveIntegerField()),
                ('photo_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('geolocalization', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
