# Generated by Django 5.2.8 on 2025-12-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
