# Generated by Django 5.2.8 on 2025-12-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_rental_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='geolocalization',
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='car',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
