# Generated by Django 5.2.8 on 2026-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_car_geolocalization_car_city_car_lat_car_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
