# Generated by Django 5.2.8 on 2026-03-18 10:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_car_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='car',
            name='lon',
        ),
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
